// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// URLGetter is an autogenerated mock type for the URLGetter type
type URLGetter struct {
	mock.Mock
}

// GetUrl provides a mock function with given fields: alias, ctx
func (_m *URLGetter) GetUrl(alias string, ctx context.Context) (string, error) {
	ret := _m.Called(alias, ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUrl")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, context.Context) (string, error)); ok {
		return rf(alias, ctx)
	}
	if rf, ok := ret.Get(0).(func(string, context.Context) string); ok {
		r0 = rf(alias, ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, context.Context) error); ok {
		r1 = rf(alias, ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewURLGetter creates a new instance of URLGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewURLGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *URLGetter {
	mock := &URLGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
