env: "local"
http_server:  
  address: "localhost:8000"
  timeout: 4s
  iddle_timeout: 60s 



storages:
  storage_path: "./storage/storage.db"
  storage_pathPG: "postgres://postgres:1234@localhost:0000/testBaseURL"

aliasLenght: 6


authorization:
  user: "myuser"
  password: "mypass"