env: "local"
http_server:
  address: "localhost:8000"
  timeout: "4s"
  idle_timeout: "60s"

storages:
  storage_path: "./storage/storage.db"
  storage_pathPG: "postgres://postgres:qwerty@localhost:5432/testBaseURL"

authorization:
  user: "myuser"
  password: "mypass"

aliasLength: 6
