// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// URLDeletter is an autogenerated mock type for the URLDeletter type
type URLDeletter struct {
	mock.Mock
}

// DeleteUrl provides a mock function with given fields: alias, ctx
func (_m *URLDeletter) DeleteUrl(alias string, ctx context.Context) (int64, error) {
	ret := _m.Called(alias, ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUrl")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(string, context.Context) (int64, error)); ok {
		return rf(alias, ctx)
	}
	if rf, ok := ret.Get(0).(func(string, context.Context) int64); ok {
		r0 = rf(alias, ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(string, context.Context) error); ok {
		r1 = rf(alias, ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewURLDeletter creates a new instance of URLDeletter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewURLDeletter(t interface {
	mock.TestingT
	Cleanup(func())
}) *URLDeletter {
	mock := &URLDeletter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
